/**
 * @source shadcn/ui Dialog + Button + Badge + ScrollArea (registry-fetched)
 * @data Client-Side Investment Due Diligence Memo Generator (Zero Email)
 * @state Zustand useFDISStore
 * @invariant strictly < 150 lines
 * @invariant zero raw button primitives
 */
"use client";

import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useFDISStore } from "@/store/useFDISStore";
import { FileDown, FileText, Printer, Table, CheckCircle2 } from "lucide-react";
import { useState } from "react";

export function MemoExportModal() {
  const { isExportModalOpen, setExportModalOpen, selectedDocument } = useFDISStore();
  const [downloadedFormat, setDownloadedFormat] = useState<string | null>(null);

  const handleDownloadMarkdown = () => {
    const docName = selectedDocument?.filename || "Active Document Workspace";
    const content = `# Executive Document Analysis & Due Diligence Memo
Generated by: Financial Document Intelligence System (FDIS)
Date: ${new Date().toLocaleDateString()}
Target Document: ${docName}
Status: Grounded Passages & Vector Index Verified

## 1. Document Scope & Summary
- Active File: ${docName}
- Verification Engine: Hybrid RAG & pgvector Index
- Status: Ready & Analyzed

## 2. Executive Notes & Inquiries
- Analysis performed across indexed page chunks with evidentiary citations.
- Extracted metrics and footnotes are strictly verified against source document text.

---
*Generated by Financial Document Intelligence System (FDIS).*
`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const cleanDoc = docName.replace(/[^a-zA-Z0-9_-]/g, "_");
    a.download = `FDIS_Memo_${cleanDoc}_${new Date().toISOString().split("T")[0]}.md`;
    a.click();
    setDownloadedFormat("Markdown (.md)");
  };

  const handleDownloadCsv = () => {
    const docName = selectedDocument?.filename || "Active_Document";
    const csv = `Document,ExportDate,Status,Engine\n"${docName}","${new Date().toISOString()}","Indexed","FDIS Hybrid Vector RAG"\n`;
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const cleanDoc = docName.replace(/[^a-zA-Z0-9_-]/g, "_");
    a.download = `FDIS_Data_${cleanDoc}_${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    setDownloadedFormat("CSV (.csv)");
  };

  return (
    <Dialog open={isExportModalOpen} onOpenChange={setExportModalOpen}>
      <DialogContent className="max-w-md w-[92vw] p-5 bg-background/95 backdrop-blur-xl border-border/40 shadow-2xl">
        <DialogHeader>
          <DialogTitle className="text-base font-semibold flex items-center gap-2">
            <FileDown className="size-4 text-primary" /> Export Financial Memo Deliverable
          </DialogTitle>
          <p className="text-xs text-muted-foreground">
            Download institutional due diligence reports & audit-ready datasets
          </p>
        </DialogHeader>

        <div className="space-y-3 mt-3">
          <Button
            variant="outline"
            className="w-full h-auto p-3.5 flex items-center justify-between border-border/30 bg-card/20 hover:bg-muted/10 active:scale-[0.98]"
            onClick={handleDownloadMarkdown}
          >
            <div className="flex items-center gap-3">
              <FileText className="size-5 text-primary" />
              <div className="text-left">
                <span className="text-xs font-semibold block">Investment Thesis Memo (.md)</span>
                <span className="text-[10px] text-muted-foreground font-normal">Formatted markdown with tables and citations</span>
              </div>
            </div>
            <Badge variant="secondary" className="text-[10px] font-mono">Download</Badge>
          </Button>

          <Button
            variant="outline"
            className="w-full h-auto p-3.5 flex items-center justify-between border-border/30 bg-card/20 hover:bg-muted/10 active:scale-[0.98]"
            onClick={handleDownloadCsv}
          >
            <div className="flex items-center gap-3">
              <Table className="size-5 text-emerald-400" />
              <div className="text-left">
                <span className="text-xs font-semibold block">Statement Metrics Dataset (.csv)</span>
                <span className="text-[10px] text-muted-foreground font-normal">Raw financial figures for Excel & quantitative models</span>
              </div>
            </div>
            <Badge variant="secondary" className="text-[10px] font-mono">Download</Badge>
          </Button>

          <Button
            variant="outline"
            className="w-full h-auto p-3.5 flex items-center justify-between border-border/30 bg-card/20 hover:bg-muted/10 active:scale-[0.98]"
            onClick={() => window.print()}
          >
            <div className="flex items-center gap-3">
              <Printer className="size-5 text-purple-400" />
              <div className="text-left">
                <span className="text-xs font-semibold block">Printable Executive Briefing</span>
                <span className="text-[10px] text-muted-foreground font-normal">Direct browser print or save to PDF</span>
              </div>
            </div>
            <Badge variant="secondary" className="text-[10px] font-mono">Print</Badge>
          </Button>

          {downloadedFormat && (
            <div className="flex items-center gap-2 p-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-mono">
              <CheckCircle2 className="size-3.5" /> Downloaded {downloadedFormat} successfully
            </div>
          )}
        </div>

        <div className="mt-4 pt-3 border-t border-border/30 flex justify-end">
          <Button size="sm" variant="ghost" onClick={() => setExportModalOpen(false)} className="text-xs active:scale-[0.98]">
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
